# Generated by Django 4.1.6 on 2023-06-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emply_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departmant',
            new_name='Department',
        ),
    ]
